### ISSUE TITLE
Make TTS packages optional

### ISSUE THREAD

**Issue by LilianBoulard** [MathBlocks/manim-voiceover#4]
I notice in the `setup.py`, all text-to-speech packages are listed in the requirements.
If for instance I wanted to only use Azure, I'd have to install the other ones unnecessarily.

There's a syntax in pip for downloading optional dependencies. See [this post](https://stackoverflow.com/a/60307740/9084059).

By default, the package could come as a framework, and it would be up to the user to install the TTS package they want to use, like that:
```commandline
pip install manim-voiceover
pip install manim-voiceover[gTTS]
```

In code, when importing a package that is not installed (such as Azure in this case), it would simply raise an error saying something along the line of "The dependencies for Azure TTS are not present, use 'pip install manim-voiceover[Azure]' to install them".

What do you think ?

**Comment by prism0x** [comment]
Sounds reasonable—it does not make a lot of difference for the current packages, but for when we add support for e.g. [Coqui's TTS](https://github.com/coqui-ai/TTS), it would be very helpful. I will add it to the TODO list in the PR.
